### ISSUE TITLE
expected bytes or bytearray, but got str

### ISSUE THREAD

**Issue by bijan588** [Aula13/poloniex#2]
```
# This program prints Hello, world!import os
import os
from poloniex import Poloniex

os.environ["POLONIEX_API_KEY"] = "[REDACTED]"
os.environ["POLONIEX_SECRET"] = "[REDACTED]"
api_key =  os.environ.get('POLONIEX_API_KEY')
api_secret = os.environ.get('POLONIEX_SECRET')

polo = Poloniex(api_key, api_secret)

ticker = polo.returnTicker()['BTC_ETH']
print(ticker)
print (os.environ)
balances = polo.returnBalances()
print(balances)


```

Gives the error  expected bytes or bytearray, but got str. . My real key is in the redacted bit. Any ideas?

**Comment by dnlcrl** [comment]
> My real key is in the redacted bit

Then you should do:

    [...]
    api_key = 'REDACTED'
    api_secret = 'REDACTED'
    [...]

**Comment by bijan588** [comment]
Hey there,

Already tried that. Like this right?

```
 import os
from poloniex import Poloniex

api_key = "XXXXX-G0XXXXGV-WXXXXXX9X-FXXXXXX6"
api_secret = "9aaeff0f420a0e8a2fXXXXXXXXXXXXXXXXXXXXXXXX9f890d232c1f80XXXXXXXXXXXXXXX176af5cf"

polo = Poloniex(api_key, api_secret)

ticker = polo.returnTicker()['BTC_ETH']
print(ticker)
print (os.environ)
balances = polo.returnBalances()
print(balances)

```


That gives:
```
###  Traceback (most recent call last):
  File "C:/Users/Dontpanic/PycharmProjects/untitled/main.py", line 13, in <module>
    balances = polo.returnBalances()
  File "C:\Users\Dontpanic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\poloniex\poloniex.py", line 154, in returnBalances
    return self._private('returnBalances')
  File "C:\Users\Dontpanic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\poloniex\poloniex.py", line 37, in _fn
    resp = fn(self, command, **params).json(object_hook=_AutoCastDict)
  File "C:\Users\Dontpanic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\poloniex\poloniex.py", line 150, in _private
    data=params, auth=Poloniex._PoloniexAuth(self._secret))
  File "C:\Users\Dontpanic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Dontpanic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 488, in request
    prep = self.prepare_request(req)
  File "C:\Users\Dontpanic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 431, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Dontpanic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 309, in prepare
    self.prepare_auth(auth, url)
  File "C:\Users\Dontpanic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 540, in prepare_auth
    r = auth(self)
  File "C:\Users\Dontpanic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\poloniex\poloniex.py", line 128, in __call__
    signature = _hmac.new(self._secret, request.body, _hashlib.sha512)
  File "C:\Users\Dontpanic\AppData\Local\Programs\Python\Python36-32\lib\hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "C:\Users\Dontpanic\AppData\Local\Programs\Python\Python36-32\lib\hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'

```

Sorry, I usually program in C++/Java, this is all new to me.

**Comment by piwi3910** [comment]
have the same issue, any resolution?

**Comment by Mantas779** [comment]
With single quotes , works with me.

polo.Key = '3ORL5JUX-BBBBB-CCCCC-AAAAAA'

**Comment by havocesp** [comment]
To 'convert' string to bytes in python just put 'b' as prefix, like this, (it is just an idea, just try it):

api_key = b"XXXXX-G0XXXXGV-WXXXXXX9X-FXXXXXX6"
api_secret = b"9aaeff0f420a0e8a2fXXXXXXXXXXXXXXXXXXXXXXXX9f890d232c1f80XXXXXXXXXXXXXXX176af5cf"
